### ISSUE TITLE
Check Collections.sort function in Matoll.java

### ISSUE THREAD

**Issue by swalter2** [ag-sc/matoll#17]
Exception in thread "main" java.lang.IllegalArgumentException: Comparison method violates its general contract!
    at java.util.TimSort.mergeHi(TimSort.java:895)
    at java.util.TimSort.mergeAt(TimSort.java:512)
    at java.util.TimSort.mergeForceCollapse(TimSort.java:453)
    at java.util.TimSort.sort(TimSort.java:250)
    at java.util.Arrays.sort(Arrays.java:1435)
    at java.util.Collections.sort(Collections.java:230)
    at de.citec.sc.matoll.process.Matoll.main(Matoll.java:370)

**Comment by swalter2** [comment]
not needed anymore
