### ISSUE TITLE
Parallelization of matoll

### ISSUE THREAD

**Issue by swalter2** [ag-sc/matoll#63]
using Java streams?!?

**Comment by swalter2** [comment]
if #64 is done, the parallelStreams() should work, as in the moment there is an out of Index error in jena/while using jena

**Comment by swalter2** [comment]
Jena is not thread safe
https://jena.apache.org/documentation/notes/concurrency-howto.html

java.lang.StringIndexOutOfBoundsException: String index out of range: 187
    at java.lang.String.<init>(String.java:199)
    at java.lang.StringBuilder.toString(StringBuilder.java:407)
    at org.apache.jena.atlas.iterator.AccString.get(AccString.java:52)
    at org.apache.jena.atlas.iterator.AccString.get(AccString.java:21)
    at org.apache.jena.atlas.iterator.Iter.reduce(Iter.java:170)
    at org.apache.jena.atlas.iterator.Iter.asString(Iter.java:428)

Using a lock does not help in this case, as the most work is done with jena. If using a lock and then multiple threads, it is the same as running files sequential
